// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsbpzmcqpmrucelpbryx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzYnB6bWNxcG1ydWNlbHBicnl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMDg1ODMsImV4cCI6MjA2Mzc4NDU4M30.2K6FViqZYvUriBaP-FaxvSX6OOaubJb0QueGh4JzSek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);